const a=[
  {
  teste: 1200,
  treino:[
      {
          semana:1,
          distancia:1600,
          tempo:18.5
      },
      {
          semana:2,
          distancia:1800,
          tempo:20.5
      },
      {
          semana:3,
          distancia:2000,
          tempo:23
      },
      {
          semana:4,
          distancia:2200,
          tempo:25.5
      },
      {
          semana:5,
          distancia:2300,
          tempo:26.5
      },
      {
          semana:6,
          distancia:2400,
          tempo:27.5
      },
      {
          semana:7,
          distancia:2200,
          tempo:24.5
      },
      {
          semana:8,
          distancia:2000,
          tempo:22
      },
      {
          semana:9,
          distancia:1900,
          tempo:20
      },
      {
          semana:10,
          distancia:1600,
          tempo:16.5
      },
  ]
  },
  {
      teste: 1300,
      treino:[
          {
              semana:1,
              distancia:1700,
              tempo:18
          },
          {
              semana:2,
              distancia:1900,
              tempo:20
          },
          {
              semana:3,
              distancia:2000,
              tempo:21
          },
          {
              semana:4,
              distancia:2200,
              tempo:23.5
          },
          {
              semana:5,
              distancia:2400,
              tempo:25.5
          },
          {
              semana:6,
              distancia:2600,
              tempo:27.5
          },
          {
              semana:7,
              distancia:2400,
              tempo:25
          },
          {
              semana:8,
              distancia:2200,
              tempo:22
          },
          {
              semana:9,
              distancia:2100,
              tempo:20.5
          },
          {
              semana:10,
              distancia:1700,
              tempo:16
          },
      ]
      },
      {
      teste: 1300,
      treino:[
          {
              semana:1,
              distancia:1700,
              tempo:18
          },
          {
              semana:2,
              distancia:1900,
              tempo:20
          },
          {
              semana:3,
              distancia:2000,
              tempo:21
          },
          {
              semana:4,
              distancia:2200,
              tempo:23.5
          },
          {
              semana:5,
              distancia:2400,
              tempo:25.5
          },
          {
              semana:6,
              distancia:2600,
              tempo:27.5
          },
          {
              semana:7,
              distancia:2400,
              tempo:25
          },
          {
              semana:8,
              distancia:2200,
              tempo:22
          },
          {
              semana:9,
              distancia:2100,
              tempo:20.5
          },
          {
              semana:10,
              distancia:1700,
              tempo:16
          },
      ]
      },
      {
          teste: 1400,
          treino:[
              {
                  semana:1,
                  distancia:1800,
                  tempo:17.5
              },
              {
                  semana:2,
                  distancia:2000,
                  tempo:19.5
              },
              {
                  semana:3,
                  distancia:2200,
                  tempo:21.5
              },
              {
                  semana:4,
                  distancia:2400,
                  tempo:23.5
              },
              {
                  semana:5,
                  distancia:2600,
                  tempo:25.5
              },
              {
                  semana:6,
                  distancia:2800,
                  tempo:27.5
              },
              {
                  semana:7,
                  distancia:2600,
                  tempo:25
              },
              {
                  semana:8,
                  distancia:2400,
                  tempo:22.5
              },
              {
                  semana:9,
                  distancia:2200,
                  tempo:20
              },
              {
                  semana:10,
                  distancia:1800,
                  tempo:16
              },
          ]
      },
      {
          teste: 1500,
          treino:[
              {
                  semana:1,
                  distancia:1900,
                  tempo:17.5
              },
              {
                  semana:2,
                  distancia:2100,
                  tempo:19.5
              },
              {
                  semana:3,
                  distancia:2300,
                  tempo:21
              },
              {
                  semana:4,
                  distancia:2500,
                  tempo:23
              },
              {
                  semana:5,
                  distancia:2700,
                  tempo:25
              },
              {
                  semana:6,
                  distancia:3000,
                  tempo:27.5
              },
              {
                  semana:7,
                  distancia:2700,
                  tempo:24
              },
              {
                  semana:8,
                  distancia:2500,
                  tempo:22
              },
              {
                  semana:9,
                  distancia:2300,
                  tempo:19.5
              },
              {
                  semana:10,
                  distancia:1900,
                  tempo:15.5
              },
          ]
      },
      {
          teste: 1600,
          treino:[
              {
                  semana:1,
                  distancia:2100,
                  tempo:18
              },
              {
                  semana:2,
                  distancia:2300,
                  tempo:20
              },
              {
                  semana:3,
                  distancia:2500,
                  tempo:21.5
              },
              {
                  semana:4,
                  distancia:2700,
                  tempo:23.5
              },
              {
                  semana:5,
                  distancia:2900,
                  tempo:25
              },
              {
                  semana:6,
                  distancia:3200,
                  tempo:27.5
              },
              {
                  semana:7,
                  distancia:2900,
                  tempo:24.5
              },
              {
                  semana:8,
                  distancia:2700,
                  tempo:22
              },
              {
                  semana:9,
                  distancia:2500,
                  tempo:20
              },
              {
                  semana:10,
                  distancia:2100,
                  tempo:16
              },
          ]
      },
      {
          teste: 1700,
          treino:[
              {
                  semana:1,
                  distancia:2200,
                  tempo:18
              },
              {
                  semana:2,
                  distancia:2400,
                  tempo:19.5
              },
              {
                  semana:3,
                  distancia:2600,
                  tempo:21
              },
              {
                  semana:4,
                  distancia:2800,
                  tempo:22.5
              },
              {
                  semana:5,
                  distancia:3000,
                  tempo:24.5
              },
              {
                  semana:6,
                  distancia:3300,
                  tempo:27
              },
              {
                  semana:7,
                  distancia:3000,
                  tempo:23.5
              },
              {
                  semana:8,
                  distancia:2800,
                  tempo:21.5
              },
              {
                  semana:9,
                  distancia:2600,
                  tempo:19.5
              },
              {
                  semana:10,
                  distancia:2200,
                  tempo:16
              },
          ]
      },
      {
          teste: 1800,
          treino:[
              {
                  semana:1,
                  distancia:2300,
                  tempo:17.5
              },
              {
                  semana:2,
                  distancia:2500,
                  tempo:19
              },
              {
                  semana:3,
                  distancia:2700,
                  tempo:20.5
              },
              {
                  semana:4,
                  distancia:2900,
                  tempo:22
              },
              {
                  semana:5,
                  distancia:3200,
                  tempo:24.5
              },
              {
                  semana:6,
                  distancia:3500,
                  tempo:27
              },
              {
                  semana:7,
                  distancia:3200,
                  tempo:24
              },
              {
                  semana:8,
                  distancia:2900,
                  tempo:21
              },
              {
                  semana:9,
                  distancia:2700,
                  tempo:19
              },
              {
                  semana:10,
                  distancia:2300,
                  tempo:16
              },
          ]
      },
      {
          teste: 1900,
          treino:[
              {
                  semana:1,
                  distancia:2500,
                  tempo:18
              },
              {
                  semana:2,
                  distancia:2700,
                  tempo:19.5
              },
              {
                  semana:3,
                  distancia:2900,
                  tempo:21
              },
              {
                  semana:4,
                  distancia:3100,
                  tempo:22.5
              },
              {
                  semana:5,
                  distancia:3400,
                  tempo:24.5
              },
              {
                  semana:6,
                  distancia:3700,
                  tempo:27
              },
              {
                  semana:7,
                  distancia:3400,
                  tempo:25
              },
              {
                  semana:8,
                  distancia:3100,
                  tempo:21.5
              },
              {
                  semana:9,
                  distancia:2900,
                  tempo:19.5
              },
              {
                  semana:10,
                  distancia:2500,
                  tempo:16.5
              },
          ]
      },
      {
          teste: 2000,
          treino:[
              {
                  semana:1,
                  distancia:2600,
                  tempo:18
              },
              {
                  semana:2,
                  distancia:2800,
                  tempo:19.5
              },
              {
                  semana:3,
                  distancia:3000,
                  tempo:20.5
              },
              {
                  semana:4,
                  distancia:3300,
                  tempo:23
              },
              {
                  semana:5,
                  distancia:3600,
                  tempo:25
              },
              {
                  semana:6,
                  distancia:4000,
                  tempo:27.5
              },
              {
                  semana:7,
                  distancia:3600,
                  tempo:24
              },
              {
                  semana:8,
                  distancia:3300,
                  tempo:21.5
              },
              {
                  semana:9,
                  distancia:3000,
                  tempo:19
              },
              {
                  semana:10,
                  distancia:2600,
                  tempo:16
              },
          ]
      },
      {
          teste: 2100,
          treino:[
              {
                  semana:1,
                  distancia:2700,
                  tempo:17.5
              },
              {
                  semana:2,
                  distancia:3000,
                  tempo:19.5
              },
              {
                  semana:3,
                  distancia:3300,
                  tempo:21.5
              },
              {
                  semana:4,
                  distancia:3600,
                  tempo:23.5
              },
              {
                  semana:5,
                  distancia:3900,
                  tempo:25.5
              },
              {
                  semana:6,
                  distancia:4100,
                  tempo:27
              },
              {
                  semana:7,
                  distancia:3900,
                  tempo:25
              },
              {
                  semana:8,
                  distancia:3600,
                  tempo:22.5
              },
              {
                  semana:9,
                  distancia:3300,
                  tempo:20
              },
              {
                  semana:10,
                  distancia:2700,
                  tempo:16
              },
          ]
      },
      {
          teste: 2200,
          treino:[
              {
                  semana:1,
                  distancia:2900,
                  tempo:18
              },
              {
                  semana:2,
                  distancia:3200,
                  tempo:20
              },
              {
                  semana:3,
                  distancia:3500,
                  tempo:22
              },
              {
                  semana:4,
                  distancia:3800,
                  tempo:24
              },
              {
                  semana:5,
                  distancia:4200,
                  tempo:26.5
              },
              {
                  semana:6,
                  distancia:4600,
                  tempo:29
              },
              {
                  semana:7,
                  distancia:4200,
                  tempo:25.5
              },
              {
                  semana:8,
                  distancia:3800,
                  tempo:22.5
              },
              {
                  semana:9,
                  distancia:3500,
                  tempo:20
              },
              {
                  semana:10,
                  distancia:2900,
                  tempo:16.5
              },
          ]
      },
      {
          teste: 2300,
          treino:[
              {
                  semana:1,
                  distancia:3000,
                  tempo:18
              },
              {
                  semana:2,
                  distancia:3300,
                  tempo:20
              },
              {
                  semana:3,
                  distancia:3600,
                  tempo:21.5
              },
              {
                  semana:4,
                  distancia:3900,
                  tempo:23.5
              },
              {
                  semana:5,
                  distancia:4300,
                  tempo:26
              },
              {
                  semana:6,
                  distancia:4700,
                  tempo:28
              },
              {
                  semana:7,
                  distancia:4300,
                  tempo:25
              },
              {
                  semana:8,
                  distancia:3900,
                  tempo:22
              },
              {
                  semana:9,
                  distancia:3600,
                  tempo:20
              },
              {
                  semana:10,
                  distancia:3000,
                  tempo:16
              },
          ]
      },
      {
          teste: 2400,
          treino:[
              {
                  semana:1,
                  distancia:3100,
                  tempo:18
              },
              {
                  semana:2,
                  distancia:3400,
                  tempo:19.5
              },
              {
                  semana:3,
                  distancia:3700,
                  tempo:21.5
              },
              {
                  semana:4,
                  distancia:4000,
                  tempo:23
              },
              {
                  semana:5,
                  distancia:4400,
                  tempo:25.5
              },
              {
                  semana:6,
                  distancia:4800,
                  tempo:27.5
              },
              {
                  semana:7,
                  distancia:4400,
                  tempo:24.5
              },
              {
                  semana:8,
                  distancia:4000,
                  tempo:22
              },
              {
                  semana:9,
                  distancia:3700,
                  tempo:19.5
              },
              {
                  semana:10,
                  distancia:3100,
                  tempo:16
              },
          ]
      },
      {
          teste: 2500,
          treino:[
              {
                  semana:1,
                  distancia:3300,
                  tempo:18
              },
              {
                  semana:2,
                  distancia:3600,
                  tempo:20
              },
              {
                  semana:3,
                  distancia:3900,
                  tempo:22
              },
              {
                  semana:4,
                  distancia:4200,
                  tempo:23.5
              },
              {
                  semana:5,
                  distancia:4600,
                  tempo:25.5
              },
              {
                  semana:6,
                  distancia:5000,
                  tempo:27.5
              },
              {
                  semana:7,
                  distancia:4600,
                  tempo:24.5
              },
              {
                  semana:8,
                  distancia:4200,
                  tempo:22
              },
              {
                  semana:9,
                  distancia:3900,
                  tempo:20
              },
              {
                  semana:10,
                  distancia:3300,
                  tempo:16.5
              },
          ]
      },
      {
          teste: 2600,
          treino:[
              {
                  semana:1,
                  distancia:3400,
                  tempo:18
              },
              {
                  semana:2,
                  distancia:3700,
                  tempo:19.5
              },
              {
                  semana:3,
                  distancia:4100,
                  tempo:22
              },
              {
                  semana:4,
                  distancia:4400,
                  tempo:23.5
              },
              {
                  semana:5,
                  distancia:4800,
                  tempo:25.5
              },
              {
                  semana:6,
                  distancia:5200,
                  tempo:27.5
              },
              {
                  semana:7,
                  distancia:4800,
                  tempo:25
              },
              {
                  semana:8,
                  distancia:4400,
                  tempo:22
              },
              {
                  semana:9,
                  distancia:4100,
                  tempo:20
              },
              {
                  semana:10,
                  distancia:3400,
                  tempo:16
              },
          ]
      },
      {
          teste: 2700,
          treino:[
              {
                  semana:1,
                  distancia:3500,
                  tempo:18
              },
              {
                  semana:2,
                  distancia:3800,
                  tempo:19.5
              },
              {
                  semana:3,
                  distancia:4200,
                  tempo:21.5
              },
              {
                  semana:4,
                  distancia:4500,
                  tempo:23
              },
              {
                  semana:5,
                  distancia:4900,
                  tempo:25
              },
              {
                  semana:6,
                  distancia:5400,
                  tempo:27.5
              },
              {
                  semana:7,
                  distancia:4900,
                  tempo:24.5
              },
              {
                  semana:8,
                  distancia:4500,
                  tempo:22
              },
              {
                  semana:9,
                  distancia:4200,
                  tempo:20
              },
              {
                  semana:10,
                  distancia:3500,
                  tempo:16
              },
          ]
      },
      {
          teste: 2800,
          treino:[
              {
                  semana:1,
                  distancia:3600,
                  tempo:17.5
              },
              {
                  semana:2,
                  distancia:3900,
                  tempo:19
              },
              {
                  semana:3,
                  distancia:4300,
                  tempo:21
              },
              {
                  semana:4,
                  distancia:4600,
                  tempo:22.5
              },
              {
                  semana:5,
                  distancia:5000,
                  tempo:24.5
              },
              {
                  semana:6,
                  distancia:5500,
                  tempo:27
              },
              {
                  semana:7,
                  distancia:5500,
                  tempo:24
              },
              {
                  semana:8,
                  distancia:4600,
                  tempo:21.5
              },
              {
                  semana:9,
                  distancia:4300,
                  tempo:19.5
              },
              {
                  semana:10,
                  distancia:3600,
                  tempo:16
              },
          ]
      },
      {
          teste: 2900,
          treino:[
              {
                  semana:1,
                  distancia:3800,
                  tempo:18
              },
              {
                  semana:2,
                  distancia:4100,
                  tempo:19.5
              },
              {
                  semana:3,
                  distancia:4400,
                  tempo:21
              },
              {
                  semana:4,
                  distancia:4800,
                  tempo:23
              },
              {
                  semana:5,
                  distancia:5200,
                  tempo:25
              },
              {
                  semana:6,
                  distancia:5700,
                  tempo:27
              },
              {
                  semana:7,
                  distancia:5200,
                  tempo:24
              },
              {
                  semana:8,
                  distancia:4800,
                  tempo:21.5
              },
              {
                  semana:9,
                  distancia:4400,
                  tempo:19.5
              },
              {
                  semana:10,
                  distancia:3800,
                  tempo:16
              },
          ]
      },
      {
          teste: 3000,
          treino:[
              {
                  semana:1,
                  distancia:3900,
                  tempo:18
              },
              {
                  semana:2,
                  distancia:4300,
                  tempo:20
              },
              {
                  semana:3,
                  distancia:4700,
                  tempo:22
              },
              {
                  semana:4,
                  distancia:5000,
                  tempo:23.5
              },
              {
                  semana:5,
                  distancia:5500,
                  tempo:25.5
              },
              {
                  semana:6,
                  distancia:6000,
                  tempo:27.5
              },
              {
                  semana:7,
                  distancia:5500,
                  tempo:24.5
              },
              {
                  semana:8,
                  distancia:5000,
                  tempo:22
              },
              {
                  semana:9,
                  distancia:4700,
                  tempo:20
              },
              {
                  semana:10,
                  distancia:3900,
                  tempo:16
              },
          ]
      },
      {
          teste: 3100,
          treino:[
              {
                  semana:1,
                  distancia:4000,
                  tempo:18
              },
              {
                  semana:2,
                  distancia:4400,
                  tempo:20
              },
              {
                  semana:3,
                  distancia:4800,
                  tempo:21.5
              },
              {
                  semana:4,
                  distancia:5300,
                  tempo:24
              },
              {
                  semana:5,
                  distancia:5800,
                  tempo:26
              },
              {
                  semana:6,
                  distancia:6300,
                  tempo:28
              },
              {
                  semana:7,
                  distancia:5800,
                  tempo:25
              },
              {
                  semana:8,
                  distancia:5300,
                  tempo:22.5
              },
              {
                  semana:9,
                  distancia:4800,
                  tempo:19.5
              },
              {
                  semana:10,
                  distancia:4000,
                  tempo:16
              },
          ]
      },
      {
          teste: 3200,
          treino:[
              {
                  semana:1,
                  distancia:4200,
                  tempo:18
              },
              {
                  semana:2,
                  distancia:4600,
                  tempo:20
              },
              {
                  semana:3,
                  distancia:5000,
                  tempo:22
              },
              {
                  semana:4,
                  distancia:5500,
                  tempo:24
              },
              {
                  semana:5,
                  distancia:6000,
                  tempo:26
              },
              {
                  semana:6,
                  distancia:6400,
                  tempo:27.5
              },
              {
                  semana:7,
                  distancia:6000,
                  tempo:25
              },
              {
                  semana:8,
                  distancia:5500,
                  tempo:22.5
              },
              {
                  semana:9,
                  distancia:5000,
                  tempo:20
              },
              {
                  semana:10,
                  distancia:4200,
                  tempo:16
              },
          ]
      },
      {
          teste: 3300,
          treino:[
              {
                  semana:1,
                  distancia:4300,
                  tempo:18
              },
              {
                  semana:2,
                  distancia:4700,
                  tempo:20
              },
              {
                  semana:3,
                  distancia:5200,
                  tempo:22
              },
              {
                  semana:4,
                  distancia:5700,
                  tempo:24
              },
              {
                  semana:5,
                  distancia:6200,
                  tempo:26
              },
              {
                  semana:6,
                  distancia:6700,
                  tempo:28
              },
              {
                  semana:7,
                  distancia:6200,
                  tempo:25.5
              },
              {
                  semana:8,
                  distancia:5700,
                  tempo:22.5
              },
              {
                  semana:9,
                  distancia:5200,
                  tempo:20
              },
              {
                  semana:10,
                  distancia:4300,
                  tempo:16
              },
          ]
      },
      {
          teste: 3400,
          treino:[
              {
                  semana:1,
                  distancia:4400,
                  tempo:18
              },
              {
                  semana:2,
                  distancia:4800,
                  tempo:19.5
              },
              {
                  semana:3,
                  distancia:5300,
                  tempo:21.5
              },
              {
                  semana:4,
                  distancia:5800,
                  tempo:23.5
              },
              {
                  semana:5,
                  distancia:6300,
                  tempo:25.5
              },
              {
                  semana:6,
                  distancia:6800,
                  tempo:27.5
              },
              {
                  semana:7,
                  distancia:6300,
                  tempo:25
              },
              {
                  semana:8,
                  distancia:5800,
                  tempo:22.5
              },
              {
                  semana:9,
                  distancia:5300,
                  tempo:20
              },
              {
                  semana:10,
                  distancia:4400,
                  tempo:16
              },
          ]
      },
      {
          teste: 3500,
          treino:[
              {
                  semana:1,
                  distancia:4600,
                  tempo:18
              },
              {
                  semana:2,
                  distancia:5000,
                  tempo:19.5
              },
              {
                  semana:3,
                  distancia:5500,
                  tempo:21.5
              },
              {
                  semana:4,
                  distancia:6000,
                  tempo:23.5
              },
              {
                  semana:5,
                  distancia:6600,
                  tempo:26
              },
              {
                  semana:6,
                  distancia:7000,
                  tempo:27.5
              },
              {
                  semana:7,
                  distancia:6600,
                  tempo:25.5
              },
              {
                  semana:8,
                  distancia:6200,
                  tempo:23
              },
              {
                  semana:9,
                  distancia:5800,
                  tempo:21
              },
              {
                  semana:10,
                  distancia:4600,
                  tempo:16
              },
          ]
      }
  ];
  export default a;